### PR TITLE
Update hosting_providers.json

### PR DESCRIPTION
**Pull request by hal-nine**
Adding Google Sites (https://sites.google.com).

### CODE REVIEW

**Review by bmw — CHANGES_REQUESTED** [review]
Thanks for the PR. Can you please follow all steps from the list at https://github.com/certbot/website#hosting-providers-list?

**Comment by hal-nine** [comment]
Changed to partial after reading categories. The rest is the same as for AppEngine above this entry.

**Review by hal-nine — COMMENTED** [review]
Changed to partial, the rest the same as for appengine, above this entry.

**Comment by bmw** [comment]
The Google App Engine entry comes from the initial version of this list which we took from https://community.letsencrypt.org/t/web-hosting-who-support-lets-encrypt. For new entries, we'd like fields like "reviewed" to be filled out and a link to documentation about the product's support as described at the part of the README I linked to above.

**Comment by hal-nine** [comment]
Added reviewed and tutorial fields.

**Comment by hal-nine** [comment]
Anything else that needs to be done?

**Review by bmw — COMMENTED** [review]
Thanks for the link about how to create a Google Site. Specifically what I we're looking for in the tutorial though is how to set up HTTPS on a Google Site.

Is it possible to create a Google Site without HTTPS? Links like https://support.google.com/sites/answer/6372878?hl=en suggest it's not and it's done automatically. If that's correct, I'd:

1. Change the `category` to full.
2. Remove the tutorial field.
3. Add an "announcement" field to a URL like https://support.google.com/domains/answer/7630973?hl=en#zippy=%2Chttps-from-web-hosts.

**Comment by bmw** [comment]
This PR hasn't seen any updates in a long time so I'm going to close this. Feel free to open a new one if you like.

**Pull request closed without merging**
