### PR TITLE
Remove leading $ from shell command snippets 

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by EdOverflow** [comment]
@bmw, when I find time, I will jump back onto this pull request and separate the changes.

**Comment by EdOverflow** [comment]
I am struggling to solve this since I accidentally made changes to my master branch in #298. :(

**Comment by bmw** [comment]
Can you [add this repo as a remote named upstream](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and then [rebase](https://help.github.com/articles/about-git-rebase/) on `upstream/master`?

**Comment by bmw** [comment]
The issue this PR aims to fix has been resolved so I'm closing this. Thanks for the PR though!

**Pull request closed without merging**
