### PR TITLE
Fixed issue #3544

### PR DESCRIPTION
**Pull request by muhammednagy**
I was trying to install certbot on RHEL7 but I had broken dependencies.I googled the error and I found that that it is already an open issue.
I edited the installation guide
thanks in advance.

### CODE REVIEW

**Comment by muhammednagy** [comment]
Thanks :)

**Comment by verne-wv** [comment]
sorry I missed this months ago ... its still not technically correct ...

today it reads                

Certbot is packaged in EPEL (Extra Packages for Enterprise Linux). To use Certbot, you must first enable the EPEL repository and enable EPEL optional channel.

which is not correct ... there is no such thing as the EPEL optional channel   :-)

what about

Certbot is packaged in EPEL (Extra Packages for Enterprise Linux). To install Certbot, you must first enable the EPEL repository. And since Certbot itself uses packages contained in the CentOS/RHEL 7 optional channel, you must also enable the optional channel repository.


sorry for not using GitHub directly ... it scares me a little  :-)

Verne

**Comment by muhammednagy** [comment]
hello @verne-wv 
check this link https://fedoraproject.org/wiki/EPEL
"You need to also enable the 'optional' repository to use EPEL packages as they depend on packages in that repository. This can be done by enabling the RHEL optional subchannel for RHN-Classic. For certificate-based subscriptions see Red Hat Subscription Management Guide. For EPEL 7, in addition to the 'optional' repository (rhel-7-server-optional-rpms), you also need to enable the 'extras' repository (rhel-7-server-extras-rpms)"

**Comment by verne-wv** [comment]
I think you have missed my point entirely.

CertBot itself requires the optional channel, and the optional channel is not inside or part of EPEL, instead it is supplied directly from the CentOS (or RHEL) repos.

**Comment by dtonhofer** [comment]
The instructions at https://certbot.eff.org/#centosrhel7-apache are still incomplete regarding Red Hat Enterprise Linux 7 running on EC2.

We read:

```
Certbot is packaged in EPEL (Extra Packages for Enterprise Linux). To use Certbot, you must first enable the EPEL repository and enable EPEL optional channel. 

Note:

If you are using ec2 you can enable optional channel by running: 

$ yum -y install yum-utils
$ yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
```

but this is still confusing (it's also a bit unreadable as one has to scroll the "code window" left and right)

How Do:

1) Enable EPEL, the repository for packages interesting to RHEL users but not supported by RH (https://fedoraproject.org/wiki/EPEL/FAQ#What_is_EPEL.3F)

`# rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm`

2) Make sure the _optional_ and _extras_ repositories of your RHEL7 instance are enabled (note that "REGION" in the command below is not a placeholder, it really is "REGION". "rhui" is the Red Hat Update Interface, under supervision of Red Hat):

```
# yum -y install yum-utils
# yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
```

Check your repos with:

`# yum repolist all`

If you want to know what packages are offered by a reol:

`yum --disablerepo="*" --enablerepo="rhui-REGION-rhel-server-optional" list available`

Now you can:

`yum search certbot`

to find:

```
python2-certbot.noarch : Python 2 libraries used by certbot
python2-certbot-apache.noarch : The apache plugin for certbot
python2-certbot-nginx.noarch : The nginx plugin for certbot
certbot.noarch : A free, automated certificate authority client
```

and install it:

`yum install certbot`

Note the dependencies:

```
===================================================================================================================================================
 Package                              Arch                 Version                            Repository                                      Size
===================================================================================================================================================
Installing:
 certbot                              noarch               0.19.0-1.el7                       epel                                            20 k
Installing for dependencies:
 dialog                               x86_64               1.2-4.20130523.el7                 rhui-REGION-rhel-server-releases               208 k
 python-cffi                          x86_64               1.6.0-5.el7                        rhui-REGION-rhel-server-releases               218 k
 python-enum34                        noarch               1.0.4-1.el7                        rhui-REGION-rhel-server-releases                52 k
 python-idna                          noarch               2.4-1.el7                          rhui-REGION-rhel-server-releases                94 k
 python-ipaddress                     noarch               1.0.16-2.el7                       rhui-REGION-rhel-server-releases                34 k
 python-ndg_httpsclient               noarch               0.3.2-1.el7                        epel                                            43 k
 python-parsedatetime                 noarch               1.5-3.el7                          epel                                            61 k
 python-ply                           noarch               3.4-11.el7                         rhui-REGION-rhel-server-releases               123 k
 python-pycparser                     noarch               2.14-1.el7                         rhui-REGION-rhel-server-releases               105 k
 python-zope-component                noarch               1:4.1.0-3.el7                      epel                                           227 k
 python-zope-event                    noarch               4.0.3-2.el7                        epel                                            79 k
 python-zope-interface                x86_64               4.0.5-4.el7                        rhui-REGION-rhel-server-optional               138 k
 python2-acme                         noarch               0.19.0-1.el7                       epel                                           176 k
 python2-certbot                      noarch               0.19.0-1.el7                       epel                                           471 k
 python2-configargparse               noarch               0.11.0-1.el7                       epel                                            30 k
 python2-cryptography                 x86_64               1.7.2-1.el7_4.1                    rhui-REGION-rhel-server-releases               502 k
 python2-dialog                       noarch               3.3.0-6.el7                        epel                                            94 k
 python2-future                       noarch               0.16.0-2.el7                       epel                                           799 k
 python2-mock                         noarch               1.0.1-9.el7                        epel                                            92 k
 python2-psutil                       x86_64               2.2.1-2.el7                        epel                                           116 k
 python2-pyasn1                       noarch               0.1.9-7.el7                        rhui-REGION-rhel-server-releases               100 k
 python2-pyrfc3339                    noarch               1.0-2.el7                          epel                                            13 k
 pytz                                 noarch               2016.10-2.el7                      rhui-REGION-rhel-server-releases                46 k

```

**Comment by SwartzCr** [comment]
@dtonhofer Is your objection that we're giving improper instructions or just that they're hard to read/understand?

**Comment by dtonhofer** [comment]
@SwartzCr Sorry for the late reply. The instructions were not improper just "too short". It was still a puzzler for me to make things work.

**Pull request merged**
