### PR TITLE
Add instructions to hosting_providers.json

### PR DESCRIPTION
**Pull request by ohemorange**

### CODE REVIEW

**Comment by bmw** [comment]
TIL there's no syntax for comments in JSON: https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by ohemorange** [comment]
do we not jsmin it? https://stackoverflow.com/a/10976934

**Comment by bmw** [comment]
I guess not. I unfortunately don't really have any familiarity with the internals of this site outside of the instruction generator. Not sure how hard it would be to change this behavior.

**Comment by ohemorange** [comment]
Ok, new plan: put the directions in the website README, and link to the anchor anywhere we say to edit this file.

**Comment by bmw** [comment]
That also works for me.

**Comment by bmw** [comment]
Tests will pass when https://github.com/certbot/website/issues/455 is resolved. I took a crack at offering a solution based on our conversation there in https://github.com/certbot/website/pull/456.

**Pull request merged**
