### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by esoterik**
the CI is failing on some broken links, investigating them today

### CODE REVIEW

**Comment by ohemorange** [comment]
Some things I noticed:

- [ ] "certbot instructions" page title is farther left than all other page titles
- [ ] bolded items on "get help" page shouldn't be links
- [ ] styling of bottom matter on hosting providers with https page doesn't match wireframe
- [ ] On the hosting providers page, the inline text "full/partial/no https support" should jump to the appropriate table
- [ ] On the contribute page, we should italicize and indent the legalese paragraphs as in the wireframe
- [ ] x button for tooltips on homepage isn't working for me
- [ ] on the get help page, "This page contains resources for learning about turning on HTTPS and the role Certbot plays in that process." HTTPS displays on its own line

Erica will fix
- [ ] community forum link on get help needs to be a link
- [ ] link to faq in get help: "installed certbot, but it’s not working" is meant to anchor but there's a typo

Things that are probably fine:
- [ ] links to /docs don't work

**Comment by wioux** [comment]
I really like the new design! Here are some things I noticed during QA -- apologies if some are unrelated to the changes in this branch or just local issues.

  - [ ] "See the list of providers" and "Get Certbot instructions" buttons on homepage do nothing
  - [ ] A number of Software/System combinations are broken (for example nginx/ubuntu xenial, apache/webhosting service)
  - [ ] Back button stops working after you hit a broken page
  - [ ] Glossary terms break out of the enclosing block -- particularly noticeable on /about
  - [ ] At the bottom of instructions, all three links (Get help, See how to work with Certbot, Donate to Certbot and EFF) point to /docs
  - [ ] Glossary definitions get stacked on top of/under each other unless you close them
  - [ ] Some glossary terms (e.g. "port 80") are too big for the viewport on mobile
  - [ ] Link to "this json file" (https://github.com/certbot/website/blob/master/_data/hosting_providers.json) on /help is broken
  - [ ] On mobile it looks like the logo should link the the homepage, but it doesn't due to a z-index issue
  - [ ] The hamburger icon should include some padding IMO. It's right on the edge of the screen, and a few times I tried to click it but instead triggered the red heart.
  - [ ] Would be nice if the hamburger menu nav links were full width / included some padding.
  - [ ] May want to `display: inline` the table of content links on /faq so they don't create a break after the +
  - [ ] +s also appear in the content section of /faq

**Comment by ohemorange** [comment]
Few more things!

- [ ] Are we still planning to include "a project of the Electronic Frontier Foundation" under the Certbot logo?
- [ ] I can't click in the search in the hosting providers table

Erica will look into
- [ ] there's an extra space after "optional if you want a wildcard cert" in the use certbot box
- [ ] oh no there's spaces after all the glossary items in "is certbot right for me", I'll do a sweep through the code
- [ ] hm, links I added to the faq entry aren't working...

is this ok?
- [ ] hosting providers table headers are in three different spots

not a problem
- I love the little heart that shows up when you hover over donate!!!

**Comment by okaysoraya** [comment]
Hi there! I've finally reunited with my beloved Internet.
First off: This looks terrific. A few things are nitpicky. I'll break up my comments to make it easier.

Desktop (1440px by 900, as well as resized to my screensize) 
+ Alignment:
        + seems to have some mismatched line-up points. The left-most part of the Certbot logo & left-most part of "certbot instructions" should line up with the other parts of the site, where the right-most part of "donate" should line up with the right-most parts of the site. 

Mobile (320px by 568) 
+ The sizing for the H2s, H3s and headers need to adjust for some awkward mobile sizes (scaled down), as the alignment is off for the top nav.
+ The sizing for some of the descriptive text could be scaled down a bit and brought closer to the headers that they're placed next to.
+ The red arrows on the front page should be right next to the last character, and not drop below to a separate line (I don't have a screenshot for this but it does it in some mobile sizes).

**Pull request merged**
