### PR TITLE
adding provider

### PR DESCRIPTION
**Pull request by radeknoone**
Adding the MyDreams innovatisons s.r.o. provider to list.

### CODE REVIEW

**Comment by schoen** [comment]
Hi @radeknoone,

Thanks for this submission!

The page you linked says that users have to take an action in the control panel in order to take advantage of the free certificate; is that correct? If so, we would categorize that as "partial" rather than "full".

**Comment by radeknoone** [comment]
Hi @schoen,

thank you to take the time to check my commit. The information in the link was wrong and now are corrected. We are offering webhosting on the ISPConfig platform with enabled the 'Let's Encrypt' / SSL option by default. Every customer have automatically LE enabled.

Thanks for review in advance!

**Comment by radeknoone** [comment]
Hi all,

may I ask you somebody to merge this commit please? Thank you...

**Comment by radeknoone** [comment]
Hi @bmw!

Would you be so kind and tell me how can I add new provider please?

**Comment by radeknoone** [comment]
@schoen: thanks!

**Pull request merged**
