### PR TITLE
Update Debian Instructions

### LINKED ISSUE #120: Debian Packaging
Certbot is in Debian testing and should be in jessie-backports soon. We should update instructions to reflect this.

### PR DESCRIPTION
**Pull request by bmw**
Fixes #120.

### CODE REVIEW

**Comment by bmw** [comment]
Test failures seem unrelated to my PR. `npm test` doesn't even start.

**Comment by pde** [comment]
LGTM.

**Comment by pde** [comment]
@vbrown608 do you know what's up with these test failures?

**Comment by SwartzCr** [comment]
I think it was due to the sphinx issue, which was also causing breakage for me locally and in my docker set-up. I've merged mark's change and am gonna kick travis where I can an merge updates and then see if I can re-up the website. Aren't layovers fun?

**Pull request merged**
