### PR TITLE
Update submodule

### PR DESCRIPTION
**Pull request by bmw**
The changes to the docs are:
```
diff --git a/docs/cli-help.txt b/docs/cli-help.txt
index 259142e6..49821a7b 100644
--- a/docs/cli-help.txt
+++ b/docs/cli-help.txt
@@ -108,9 +108,9 @@ optional arguments:
                         case, and to know when to deprecate support for past
                         Python versions and flags. If you wish to hide this
                         information from the Let's Encrypt server, set this to
-                        "". (default: CertbotACMEClient/0.24.0 (certbot;
-                        darwin 10.13.4) Authenticator/XXX Installer/YYY
-                        (SUBCOMMAND; flags: FLAGS) Py/2.7.14). The flags
+                        "". (default: CertbotACMEClient/0.25.1 (certbot;
+                        darwin 10.13.5) Authenticator/XXX Installer/YYY
+                        (SUBCOMMAND; flags: FLAGS) Py/2.7.15). The flags
                         encoded in the user agent are: --duplicate, --force-
                         renew, --allow-subset-of-names, -n, and whether any
                         hooks are set.
@@ -143,6 +143,8 @@ automation:
                         certificate name but does not match the requested
                         domains, renew it now, regardless of whether it is
                         near expiry. (default: False)
+  --reuse-key           When renewing, use the same private key as the
+                        existing certificate. (default: False)
   --allow-subset-of-names
                         When performing domain validation, do not consider it
                         a failure if authorizations can not be obtained for a
@@ -319,6 +321,13 @@ renew:
                         disable it. (default: False)
   --no-directory-hooks  Disable running executables found in Certbot's hook
                         directories during renewal. (default: False)
+  --disable-renew-updates
+                        Disable automatic updates to your server configuration
+                        that would otherwise be done by the selected installer
+                        plugin, and triggered when the user executes "certbot
+                        renew", regardless of if the certificate is renewed.
+                        This setting does not apply to important TLS
+                        configuration updates. (default: False)
 
 certificates:
   List certificates managed by Certbot
@@ -360,8 +369,9 @@ register:
                         e-mail address, should be updated, rather than
                         registering a new account. (default: False)
   -m EMAIL, --email EMAIL
-                        Email used for registration and recovery contact.
-                        Email used for registration and recovery contact.
-                        (default: Ask)
+                        Email used for registration and recovery contact. Use
+                        comma to register multiple emails, ex:
+                        u1@example.com,u2@example.com. (default: Ask).
   --eff-email           Share your e-mail address with EFF (default: None)
   --no-eff-email        Don't share your e-mail address with EFF (default:
                         None)
@@ -399,7 +409,7 @@ update_symlinks:
   changed them by hand or edited a renewal configuration file
 
 enhance:
-  Helps to harden the TLS configration by adding security enhancements to
+  Helps to harden the TLS configuration by adding security enhancements to
   already existing configuration.
 
 plugins:
@@ -472,9 +482,9 @@ apache:
                         /etc/apache2/other)
   --apache-handle-modules APACHE_HANDLE_MODULES
                         Let installer handle enabling required modules for
-                        you.(Only Ubuntu/Debian currently) (default: False)
+                        you. (Only Ubuntu/Debian currently) (default: False)
   --apache-handle-sites APACHE_HANDLE_SITES
-                        Let installer handle enabling sites for you.(Only
+                        Let installer handle enabling sites for you. (Only
                         Ubuntu/Debian currently) (default: False)
 
 certbot-route53:auth:
@@ -628,7 +638,8 @@ nginx:
   Nginx Web Server plugin - Alpha
 
   --nginx-server-root NGINX_SERVER_ROOT
-                        Nginx server root directory. (default: /etc/nginx)
+                        Nginx server root directory. (default:
+                        /usr/local/etc/nginx)
   --nginx-ctl NGINX_CTL
                         Path to the 'nginx' binary, used for 'configtest' and
                         retrieving nginx version number. (default: nginx)
diff --git a/docs/contributing.rst b/docs/contributing.rst
index ed986c56..58db251d 100644
--- a/docs/contributing.rst
+++ b/docs/contributing.rst
@@ -312,6 +312,40 @@ Please:
 .. _PEP 8 - Style Guide for Python Code:
   https://www.python.org/dev/peps/pep-0008
 
+Mypy type annotations
+=====================
+
+Certbot uses the `mypy`_ static type checker. Python 3 natively supports official type annotations,
+which can then be tested for consistency using mypy. Python 2 doesn’t, but type annotations can
+be `added in comments`_. Mypy does some type checks even without type annotations; we can find
+bugs in Certbot even without a fully annotated codebase.
+
+Certbot supports both Python 2 and 3, so we’re using Python 2-style annotations.
+
+Zulip wrote a `great guide`_ to using mypy. It’s useful, but you don’t have to read the whole thing
+to start contributing to Certbot.
+
+To run mypy on Certbot, use ``tox -e mypy`` on a machine that has Python 3 installed.
+
+Note that instead of just importing ``typing``, due to packaging issues, in Certbot we import from
+``acme.magic_typing`` and have to add some comments for pylint like this:
+
+.. code-block:: python
+
+  from acme.magic_typing import Dict # pylint: disable=unused-import, no-name-in-module
+
+Also note that OpenSSL, which we rely on, has type definitions for crypto but not SSL. We use both.
+Those imports should look like this:
+
+.. code-block:: python
+
+  from OpenSSL import crypto
+  from OpenSSL import SSL # type: ignore # https://github.com/python/typeshed/issues/2052
+
+.. _mypy: https://mypy.readthedocs.io
+.. _added in comments: https://mypy.readthedocs.io/en/latest/cheat_sheet.html
+.. _great guide: https://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/
+
 Submitting a pull request
 =========================
 
diff --git a/docs/using.rst b/docs/using.rst
index 40d8f845..46599a06 100644
--- a/docs/using.rst
+++ b/docs/using.rst
@@ -454,6 +454,12 @@ Renewing certificates
    days). Make sure you renew the certificates at least once in 3
    months.
 
+.. seealso:: Many of the certbot clients obtained through a
+   distribution come with automatic renewal out of the box,
+   such as Debian and Ubuntu versions installed through `apt`,
+   CentOS/RHEL 7 through EPEL, etc.  See `Automated Renewals`_
+   for more details.
+
 As of version 0.10.0, Certbot supports a ``renew`` action to check
 all installed certificates for impending expiry and attempt to renew
 them. The simplest form is simply
@@ -560,12 +566,6 @@ can run on a regular basis, like every week or every day). In that case,
 you are likely to want to use the ``-q`` or ``--quiet`` quiet flag to
 silence all output except errors.
 
-.. seealso:: Many of the certbot clients obtained through a
-   distribution come with automatic renewal out of the box,
-   such as Debian and Ubuntu versions installed through `apt`,
-   CentOS/RHEL 7 through EPEL, etc.  See `Automated Renewals`_
-   for more details.
-
 If you are manually renewing all of your certificates, the
 ``--force-renewal`` flag may be helpful; it causes the expiration time of
 the certificate(s) to be ignored when considering renewal, and attempts to
```

### CODE REVIEW

**Comment by ohemorange** [comment]
Neat: since you generated this on Mac, it changes the help text:
```
   --nginx-server-root NGINX_SERVER_ROOT
-                        Nginx server root directory. (default: /etc/nginx)
+                        Nginx server root directory. (default:
+                        /usr/local/etc/nginx)
```
I think that means that it'll show the correct one on a particular system; we probably want it to list both in the help docs.

**Comment by bmw** [comment]
> I think that means that it'll show the correct one on a particular system

I agree it should which is nice.

> we probably want it to list both in the help docs.

Nice catch!

This is related to https://github.com/certbot/certbot/pull/6120. Are you able to review that and I can address this once we have a general mechanism for fixing values like this in our docs?

Up to you if you want to block this PR on getting those changes in.

**Comment by ohemorange** [comment]
certbot/certbot#6120 is in. Let's fix the Nginx thing first.

**Comment by bmw** [comment]
New diff is:
```
diff --git a/docs/cli-help.txt b/docs/cli-help.txt
index 259142e6..594bcfd0 100644
--- a/docs/cli-help.txt
+++ b/docs/cli-help.txt
@@ -108,12 +108,12 @@ optional arguments:
                         case, and to know when to deprecate support for past
                         Python versions and flags. If you wish to hide this
                         information from the Let's Encrypt server, set this to
-                        "". (default: CertbotACMEClient/0.24.0 (certbot;
-                        darwin 10.13.4) Authenticator/XXX Installer/YYY
-                        (SUBCOMMAND; flags: FLAGS) Py/2.7.14). The flags
-                        encoded in the user agent are: --duplicate, --force-
-                        renew, --allow-subset-of-names, -n, and whether any
-                        hooks are set.
+                        "". (default: CertbotACMEClient/0.25.1
+                        (certbot(-auto); OS_NAME OS_VERSION) Authenticator/XXX
+                        Installer/YYY (SUBCOMMAND; flags: FLAGS)
+                        Py/major.minor.patchlevel). The flags encoded in the
+                        user agent are: --duplicate, --force-renew, --allow-
+                        subset-of-names, -n, and whether any hooks are set.
   --user-agent-comment USER_AGENT_COMMENT
                         Add a comment to the default user agent string. May be
                         used when repackaging Certbot or calling it from
@@ -143,6 +143,8 @@ automation:
                         certificate name but does not match the requested
                         domains, renew it now, regardless of whether it is
                         near expiry. (default: False)
+  --reuse-key           When renewing, use the same private key as the
+                        existing certificate. (default: False)
   --allow-subset-of-names
                         When performing domain validation, do not consider it
                         a failure if authorizations can not be obtained for a
@@ -319,6 +321,13 @@ renew:
                         disable it. (default: False)
   --no-directory-hooks  Disable running executables found in Certbot's hook
                         directories during renewal. (default: False)
+  --disable-renew-updates
+                        Disable automatic updates to your server configuration
+                        that would otherwise be done by the selected installer
+                        plugin, and triggered when the user executes "certbot
+                        renew", regardless of if the certificate is renewed.
+                        This setting does not apply to important TLS
+                        configuration updates. (default: False)
 
 certificates:
   List certificates managed by Certbot
@@ -360,8 +369,9 @@ register:
                         e-mail address, should be updated, rather than
                         registering a new account. (default: False)
   -m EMAIL, --email EMAIL
-                        Email used for registration and recovery contact.
-                        (default: Ask)
+                        Email used for registration and recovery contact. Use
+                        comma to register multiple emails, ex:
+                        u1@example.com,u2@example.com. (default: Ask).
   --eff-email           Share your e-mail address with EFF (default: None)
   --no-eff-email        Don't share your e-mail address with EFF (default:
                         None)
@@ -399,7 +409,7 @@ update_symlinks:
   changed them by hand or edited a renewal configuration file
 
 enhance:
-  Helps to harden the TLS configration by adding security enhancements to
+  Helps to harden the TLS configuration by adding security enhancements to
   already existing configuration.
 
 plugins:
@@ -472,9 +482,9 @@ apache:
                         /etc/apache2/other)
   --apache-handle-modules APACHE_HANDLE_MODULES
                         Let installer handle enabling required modules for
-                        you.(Only Ubuntu/Debian currently) (default: False)
+                        you. (Only Ubuntu/Debian currently) (default: False)
   --apache-handle-sites APACHE_HANDLE_SITES
-                        Let installer handle enabling sites for you.(Only
+                        Let installer handle enabling sites for you. (Only
                         Ubuntu/Debian currently) (default: False)
 
 certbot-route53:auth:
@@ -628,7 +638,8 @@ nginx:
   Nginx Web Server plugin - Alpha
 
   --nginx-server-root NGINX_SERVER_ROOT
-                        Nginx server root directory. (default: /etc/nginx)
+                        Nginx server root directory. (default: /etc/nginx or
+                        /usr/local/etc/nginx)
   --nginx-ctl NGINX_CTL
                         Path to the 'nginx' binary, used for 'configtest' and
                         retrieving nginx version number. (default: nginx)
diff --git a/docs/contributing.rst b/docs/contributing.rst
index ed986c56..58db251d 100644
--- a/docs/contributing.rst
+++ b/docs/contributing.rst
@@ -312,6 +312,40 @@ Please:
 .. _PEP 8 - Style Guide for Python Code:
   https://www.python.org/dev/peps/pep-0008
 
+Mypy type annotations
+=====================
+
+Certbot uses the `mypy`_ static type checker. Python 3 natively supports official type annotations,
+which can then be tested for consistency using mypy. Python 2 doesn’t, but type annotations can
+be `added in comments`_. Mypy does some type checks even without type annotations; we can find
+bugs in Certbot even without a fully annotated codebase.
+
+Certbot supports both Python 2 and 3, so we’re using Python 2-style annotations.
+
+Zulip wrote a `great guide`_ to using mypy. It’s useful, but you don’t have to read the whole thing
+to start contributing to Certbot.
+
+To run mypy on Certbot, use ``tox -e mypy`` on a machine that has Python 3 installed.
+
+Note that instead of just importing ``typing``, due to packaging issues, in Certbot we import from
+``acme.magic_typing`` and have to add some comments for pylint like this:
+
+.. code-block:: python
+
+  from acme.magic_typing import Dict # pylint: disable=unused-import, no-name-in-module
+
+Also note that OpenSSL, which we rely on, has type definitions for crypto but not SSL. We use both.
+Those imports should look like this:
+
+.. code-block:: python
+
+  from OpenSSL import crypto
+  from OpenSSL import SSL # type: ignore # https://github.com/python/typeshed/issues/2052
+
+.. _mypy: https://mypy.readthedocs.io
+.. _added in comments: https://mypy.readthedocs.io/en/latest/cheat_sheet.html
+.. _great guide: https://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/
+
 Submitting a pull request
 =========================
 
diff --git a/docs/using.rst b/docs/using.rst
index 40d8f845..46599a06 100644
--- a/docs/using.rst
+++ b/docs/using.rst
@@ -454,6 +454,12 @@ Renewing certificates
    days). Make sure you renew the certificates at least once in 3
    months.
 
+.. seealso:: Many of the certbot clients obtained through a
+   distribution come with automatic renewal out of the box,
+   such as Debian and Ubuntu versions installed through `apt`,
+   CentOS/RHEL 7 through EPEL, etc.  See `Automated Renewals`_
+   for more details.
+
 As of version 0.10.0, Certbot supports a ``renew`` action to check
 all installed certificates for impending expiry and attempt to renew
 them. The simplest form is simply
@@ -560,12 +566,6 @@ can run on a regular basis, like every week or every day). In that case,
 you are likely to want to use the ``-q`` or ``--quiet`` quiet flag to
 silence all output except errors.
 
-.. seealso:: Many of the certbot clients obtained through a
-   distribution come with automatic renewal out of the box,
-   such as Debian and Ubuntu versions installed through `apt`,
-   CentOS/RHEL 7 through EPEL, etc.  See `Automated Renewals`_
-   for more details.
-
 If you are manually renewing all of your certificates, the
 ``--force-renewal`` flag may be helpful; it causes the expiration time of
 the certificate(s) to be ignored when considering renewal, and attempts to
```

**Comment by bmw** [comment]
Docs diff from the previous diff is the following as expected:
```
diff --git a/docs/cli-help.txt b/docs/cli-help.txt
index 49821a7b..594bcfd0 100644
--- a/docs/cli-help.txt
+++ b/docs/cli-help.txt
@@ -108,12 +108,12 @@ optional arguments:
                         case, and to know when to deprecate support for past
                         Python versions and flags. If you wish to hide this
                         information from the Let's Encrypt server, set this to
-                        "". (default: CertbotACMEClient/0.25.1 (certbot;
-                        darwin 10.13.5) Authenticator/XXX Installer/YYY
-                        (SUBCOMMAND; flags: FLAGS) Py/2.7.15). The flags
-                        encoded in the user agent are: --duplicate, --force-
-                        renew, --allow-subset-of-names, -n, and whether any
-                        hooks are set.
+                        "". (default: CertbotACMEClient/0.25.1
+                        (certbot(-auto); OS_NAME OS_VERSION) Authenticator/XXX
+                        Installer/YYY (SUBCOMMAND; flags: FLAGS)
+                        Py/major.minor.patchlevel). The flags encoded in the
+                        user agent are: --duplicate, --force-renew, --allow-
+                        subset-of-names, -n, and whether any hooks are set.
   --user-agent-comment USER_AGENT_COMMENT
                         Add a comment to the default user agent string. May be
                         used when repackaging Certbot or calling it from
@@ -638,7 +638,7 @@ nginx:
   Nginx Web Server plugin - Alpha
 
   --nginx-server-root NGINX_SERVER_ROOT
-                        Nginx server root directory. (default:
+                        Nginx server root directory. (default: /etc/nginx or
                         /usr/local/etc/nginx)
   --nginx-ctl NGINX_CTL
                         Path to the 'nginx' binary, used for 'configtest' and
```

**Pull request merged**
