### PR TITLE
Update grammar and base styles.

### PR DESCRIPTION
**Pull request by EdOverflow**

### CODE REVIEW

**Comment by pde** [comment]
@vbrown608 do you have time to review these CSS changes?

**Comment by vbrown608** [comment]
I like these changes to h4 the pre blocks in to the instruction widget. Thanks for the attention to detail! 

Looks like we're only outputting the code tag on https://certbot.eff.org/privacy/. The 15px left and right padding looks wide to me there.

**Comment by EdOverflow** [comment]
Whoops, did not notice that. Fixed it now, @vbrown608.

**Comment by vbrown608** [comment]
Looks good to me.

**Pull request merged**
