### PR TITLE
improve rhel documentation

### PR DESCRIPTION
**Pull request by SwartzCr**
as proposed in issue #183

### CODE REVIEW

**Comment by jsoref** [comment]
LGTM

**Comment by jsoref** [comment]
For reference, the alternative command mentioned in https://access.redhat.com/documentation/en-US/Red_Hat_Subscription_Management/1/html/RHSM/supplementary-repos.html is:
`subscription-manager repos --enable rhel-6-server-optional-rpms`

**Comment by SwartzCr** [comment]
@bmw thoughts?

**Comment by bmw** [comment]
The page linked to about EPEL at the top tells you to enable the optional repository as well. Since this is link is only displayed for RHEL6 users, perhaps we should just change the text to "enable the optional and EPEL (Extra Packages for Enterprise Linux) repositories".

If we want to tell users the commands ourselves, I think we need:
1. The command to run depending on your setup (which I guess we have now?)
2. The way for users to tell which command they should run.
3. A way to test/verify that our instructions are correct.

I'm not against doing this, but if we have those 3 things, I think we can just resolve certbot/certbot#3433, remove the entirely like we did for CentOS6, and not add this documentation.

**Comment by jsoref** [comment]
My system didn't have the subscription manager installed ...

**Comment by SwartzCr** [comment]
@jsoref any other recommendations?
@bmw what steps do we need to get a workable suggestion?

**Comment by bmw** [comment]
At the very least we still need number 3 in my list above. Number 2 may have been taken care of by the comment about subscription manager if that's a robust way to check.

**Comment by SwartzCr** [comment]
@jsoref would you like to comment on #195 which relates to certbot issue https://github.com/certbot/certbot/issues/3544

**Comment by verne-wv** [comment]
not sure of the best wording without getting too verbose ... the basic RHEL7 issue is ... certbot uses python-zope-interface and its repo location changed from RHEL6 to RHEL7 ... so you could take the position ...

in regards to the module python-zope-interface, its certbot itself (directly) that needs the Optional channel for RHEL7 (in order to find python-zope-interface on RHEL7)   ... BTW writing all this from memory (no current testing or logs to verify)

**Comment by SwartzCr** [comment]
Would anyone able to test these instructions please do so?

**Comment by SwartzCr** [comment]
Still waiting for confirmation from a RHEL user that these instructions are correct - @jsoref would you be willing to review them?

**Comment by jsoref** [comment]
Yeah, I should be able to review (albeit not quite right now).

Fwiw, if you can do your testing in under an hour, you can use Google Compute Engine to pay $0.06 for a rhel-6 license (on top of the billing for the cpu):
https://cloud.google.com/compute/pricing#premiumimages

Google offers $300 worth of a free trial, so it should be quite managable for someone to do this.

**Comment by SwartzCr** [comment]
https://github.com/certbot/website/pull/208#issuecomment-325484823 should also be taken into account

**Comment by aclark4life** [comment]
You can also manually install https://www.rpmfind.net/linux/RPM/centos/7.4.1708/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.html on Redhat 7 to work around this issue e.g.

```
$ curl -O ftp://195.220.108.108/linux/centos/7.4.1708/os/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.rpm
$ sudo rpm -Uvh python-zope-interface-4.0.5-4.el7.x86_64.rpm 
$ sudo yum install certbot
…
Installed:
  certbot.noarch 0:0.18.1-1.el7                                                                                                                                     

Dependency Installed:
  dialog.x86_64 0:1.2-4.20130523.el7     python-cffi.x86_64 0:1.6.0-5.el7             python-enum34.noarch 0:1.0.4-1.el7        python-idna.noarch 0:2.4-1.el7     
  python-ipaddress.noarch 0:1.0.16-2.el7 python-ndg_httpsclient.noarch 0:0.3.2-1.el7  python-parsedatetime.noarch 0:1.5-3.el7   python-ply.noarch 0:3.4-11.el7     
  python-pycparser.noarch 0:2.14-1.el7   python-zope-component.noarch 1:4.1.0-3.el7   python-zope-event.noarch 0:4.0.3-2.el7    python2-acme.noarch 0:0.18.1-2.el7 
  python2-certbot.noarch 0:0.18.1-1.el7  python2-configargparse.noarch 0:0.11.0-1.el7 python2-cryptography.x86_64 0:1.7.2-1.el7 python2-dialog.noarch 0:3.3.0-6.el7
  python2-future.noarch 0:0.16.0-2.el7   python2-mock.noarch 0:1.0.1-9.el7            python2-psutil.x86_64 0:2.2.1-2.el7       python2-pyasn1.noarch 0:0.1.9-7.el7
  python2-pyrfc3339.noarch 0:1.0-2.el7   pytz.noarch 0:2016.10-2.el7                 

Complete!
```

**Comment by bmw** [comment]
Since RHN classic is no longer receiving updates according to https://access.redhat.com/articles/2979901, I think we need to use subscription manager here. Ideally we can just add commands before running `certbot-auto` for RHEL6 that enables the optional and EPEL repos in a way that doesn't cause errors or problems if the repos are already enabled.

**Pull request closed without merging**
